package com.airtel.iq.contants;

public enum RequestMessageType {
PLAY_AUDIO_REQ, PLAY_COLLECT_AUDIO_REQ, STOP_AUDIO_REQ, ADD_PARTICIPANT_REQ, CALL_REQ, CALL_RECORD_REQ,
	REMOVE_PARTICIPANT_REQ, SESSION_REQ, SEND_DTMF_REQ, COLLECT_DTMF_REQ, WAIT_OVER, PLAY_AUDIO_BEFORE_ANSWER_REQ,
	LEGWISE_RECORD_REQ,

	MUTE_PARTICIPANTS_REQ, UN_MUTE_PARTICIPANTS_REQ, PUT_PARTICIPANTS_ON_HOLD_REQ, UN_HOLD_PARTICIPANTS_REQ;
}
